#server:
#  port: 
#  address: 192.168.43.85
#  ssl:
#    key-password: changeit
#    key-store: @project.basedir@/secrets/ssl-server.jks
server:
  port: 8005
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:nt-ms.jks
    key-store-password: changeit
    key-alias: nt-ms
    key-store-type: JKS
    key-store-provider: SUN
    trust-store: classpath:nt-ms.jks
    trust-store-password: changeit
    trust-store-type: JKS